server:
  port: 8080
  servlet:
    context-path: /identity-service

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/identity-service
    username: root
    password: Zxcqwe098570
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

jwt:
  signerKey: "XQ47W1NPw+GHEdMGeqeuWdz9aHSBs+ZPO6chivhNunEUN41GMP+Ls/nInU6LRoZk"
  valid-duration: 30 #in seconds
  refreshable-duration: 120 #in seconds
